### ISSUE TITLE
Test runtime is very long

### ISSUE THREAD

**Issue by kaspnilsson** [samccone/fried-twinkie#5]
Hey Sam, 

Thanks for your help writing these tests for PG! It's helped catch a ton of errors for us.
That being said, the test runtime is super long and pretty inconvenient for local development, and also has caused some timeouts on our (externally hosted) CI.  I'm totally unfamiliar with this lib, is there any low-hanging fruit wrt efficiency I could help work on?

Thanks!

**Comment by samccone** [comment]
Hey yeah there are a few options.

1. stop using the JS version of closure compiler 
2. figure out how to batch up your tests vs running 1 test for every element)

I think 2 would be the easy fix here.

Essentially when we call into checkTemplate, we would make it take an object so that here
https://github.com/samccone/fried-twinkie/blob/62f9c458c5f8bdb684145b9d7d581998ddad6593/index.ts#L156

we can generate a ton of different tests for each element.

There are some downsides here such as the compiler not giving us all of the errors at once but there are some things we can do to fix this.. (on failure break out the runs into each test case)

**Comment by samccone** [comment]
Alright, I spent a few hours today implementing this feature.

Here is how to use it to check multiple elements in 1 pass
https://github.com/samccone/fried-twinkie/blob/much_faster/test.ts#L24

I would love it if you could give it a go on your app
npm install fried-twinkie@beta

**Comment by samccone** [comment]
fixed in v0.2.0
